import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="https://www.figma.com/file/nYHtL0SXomqfRy9Kd3kl7p/Untitled?node-id=1%3A15"/>
      </main>

    </div>
  )
}
