import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      
      <div className={styles.head}>
      <img src='/logo.png'
      alt='Logo'/>
        <p>Papet</p>
      </div>
    </div>
  )
}
